# .docker-compose.yml
services:
  backend:
    build:
      context: "./Backend"
      dockerfile: Dockerfile
    container_name: rag-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      FLASK_APP: myapp

  frontend:
    build:
      context: "./Frontend"
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
