version: '3'
services:
  backend:
    build:
<<<<<<< HEAD
      context: "./Backend"
=======
      context: "./Backend (RAG Model)"
>>>>>>> 5fbb05508b34de4b19f44880df54e731c1e8d4a8
      dockerfile: Dockerfile
    container_name: rag-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=myapp:create_app
    env_file:
      - .env
  frontend:
    build:
<<<<<<< HEAD
      context: "./Frontend"
=======
      context: "./Frontend (Interactive QA Bot)"
>>>>>>> 5fbb05508b34de4b19f44880df54e731c1e8d4a8
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
